services:
  analyzer:
    build: "./analyzer"
    volumes:
      - "analyzer-out:/out"
      - type: bind
        source: ${VIS_REPOSITORY_PATH}
        target: /repo/${VIS_REPOSITORY_NAME}
        read_only: true
  frontend:
    build: "./frontend"
    ports:
      - "${VIS_PORT}:5173"
    volumes:
      - "analyzer-out:/out:ro"
    depends_on:
      analyzer:
        condition: service_completed_successfully

volumes:
  analyzer-out:
